module:
  hugoVersion:
    min: "0.64.0"
  mounts:
  - source: partials
    target: layouts/partials/tnd-tailwindcss
  - source: assets
    target: assets/tnd-tailwindcss
  - source: console
    target: layouts/partials/tnd-tailwindcss
